---
language: php

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: COMPOSER_FLAGS='--ignore-platform-reqs'
    - php: 7.2
      env: DEPENDENCIES='dev' COMPOSER_FLAGS='--ignore-platform-reqs'
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
  - composer update $COMPOSER_FLAGS

script:
  - bin/phpcs src
  - bin/phpspec run --format=pretty
  - bin/behat --format=progress
...
